artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/rizal-muhammed/datasets/raw/main/wafer-fault-data.zip
  local_data_file: artifacts/data_ingestion/wafer-fault-data.zip
  unzip_dir: artifacts/data_ingestion